#!/bin/sh

# This script takes the following parameters
repo=$1
pkgname=$2

buildbot_base=/srv/buildbot/slave
script_dir=$buildbot_base/scripts
chroot_base=$buildbot_base/chroots

arch=x86_64

# do some preliminary checks
[[ -z $repo ]]    && { echo "Usage: $0 repo pkgname"; exit 1; }
[[ -z $pkgname ]] && { echo "Usage: $0 repo pkgname"; exit 1; }

# unfortunately buildbot does not recognize current directory
"$script_dir"/build $repo $pkgname $arch
