#!/bin/sh

# This script takes the following parameters
repo=$1
pkgname=$2

arch=x86_64

# do some preliminary checks
[[ -z $repo ]]    && { echo "Usage: $0 repo pkgname"; exit 1; }
[[ -z $pkgname ]] && { echo "Usage: $0 repo pkgname"; exit 1; }

scripts/build $repo $pkgname $arch
