#!/bin/sh

base_dir="chroots"

[[ -z $base_dir ]] && { echo "Usage: $0 /path/to/chroot-base"; exit 1; }

set -e
set -u

cd $base_dir

echo "creating chroots for all architectures..."
for arch in i686 x86_64 ; do
  echo "processing architecture $arch"

  if [ ! -d $arch ]; then
    mkdir $arch
    sudo setarch "${arch}" mkarchroot \
      -C pacman.${arch}.conf \
      -M makepkg.${arch}.conf \
      $arch/root \
      base-devel

  fi

done

