#!/bin/bash
# Absolute path to this script. e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f $0)
# Absolute path this script is in. e.g. /home/user/bin
SCRIPTPATH=`dirname $SCRIPT`

chroot_base=$SCRIPTPATH/../chroots

sudo rm -rf ${chroot_base}/i686
sudo rm -rf ${chroot_base}/x86_64
